on:
  push

name: Caerus Unit Testing

jobs:
  test:
    name: Test app routing and database
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Decrypt oauth-client.json
      run: ./.github/scripts/decrypt.sh
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test app routing
      run: python app/test.py
    - name: Test database functions
      run: |
        cd app
        python -m pytest